#!/usr/bin/env python3
"""sync-mcp.py — Generate native config for Claude Code, Copilot CLI, VS Code Copilot Chat, Grok.

This script is the canonical generator for the MCP configuration files.
It reads mcp.servers.toml and maps each server (by scope) into the target CLIs.

Usage:
    python .eposforge/tool-transport/mcp-stdio-and-http/scripts/sync-mcp.py [--user]
    python .eposforge/tool-transport/mcp-stdio-and-http/scripts/sync-mcp.py --check

--user: update $HOME configurations as well as project configurations.
--check: regenerates to memory, diffs against on-disk, exits non-zero on drift.
"""

import difflib
import json
import os
import pathlib
import sys
import tempfile

if sys.version_info < (3, 11):
    print("ERROR: sync-mcp.py requires Python 3.11 or newer.", file=sys.stderr)
    sys.exit(1)

import tomllib

_SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
_MCP_ADAPTER_DIR = _SCRIPT_DIR.parent
_REPO_ROOT = _MCP_ADAPTER_DIR.parent.parent.parent

_TOML_SOURCE = _MCP_ADAPTER_DIR / "mcp.servers.toml"
_SECRETS_ROOT = _REPO_ROOT / ".eposforge" / "secrets-key-management"
_EPOS_SECRETS = _REPO_ROOT / ".eposforge" / "secrets-key-management" / "bin" / "epos-secrets"

_GENERATOR_NOTE = "sync-mcp.py — DO NOT EDIT, edit mcp.servers.toml instead"
_TOML_GENERATOR_HEADER = f"# Generated by {_GENERATOR_NOTE}\n\n"

if sys.platform == "win32":
    _VSCODE_USER = pathlib.Path(os.environ.get("APPDATA", "")) / "Code" / "User" / "mcp.json"
elif sys.platform == "darwin":
    _VSCODE_USER = pathlib.Path.home() / "Library" / "Application Support" / "Code" / "User" / "mcp.json"
else:
    _VSCODE_USER = pathlib.Path.home() / ".config" / "Code" / "User" / "mcp.json"

DEV_PRODUCTS = [
    {
        "name": "Claude Code",
        "format": "mcpServers",
        "project_path": _REPO_ROOT / ".mcp.json",
        "user_path": pathlib.Path.home() / ".claude.json",
    },
    {
        "name": "Copilot CLI",
        "format": "copilot_cli",
        "project_path": _REPO_ROOT / ".github" / "mcp.json",
        "user_path": pathlib.Path.home() / ".copilot" / "mcp-config.json",
    },
    {
        "name": "VS Code Copilot Chat",
        "format": "servers",
        "project_path": _REPO_ROOT / ".vscode" / "mcp.json",
        "user_path": _VSCODE_USER,
    },
    {
        "name": "Grok",
        "format": "toml_mcp_servers",
        "project_path": _REPO_ROOT / ".grok" / "config.toml",
        "user_path": pathlib.Path.home() / ".grok" / "config.toml",
    }
]

def _build_runtime_name_map() -> dict[str, str]:
    mapping: dict[str, str] = {}
    for toml_path in sorted(_SECRETS_ROOT.glob("*/secrets.toml")):
        try:
            with toml_path.open("rb") as fh:
                data = tomllib.load(fh)
            for secret in data.get("secret", []):
                mapping[secret["logical_name"]] = secret["runtime_name"]
        except Exception as e:
            print(f"ERROR: failed to parse {toml_path}: {e}", file=sys.stderr)
            sys.exit(1)
    return mapping

def _substitute_env_vars(value: str) -> str:
    return value.replace("${REPO_ROOT}", str(_REPO_ROOT).replace("\\", "/"))

def _build_env_block(server: dict, runtime_map: dict[str, str]) -> dict[str, str]:
    non_secret = server.get("non_secret_env", {})
    result = {}
    secret_runtimes = {runtime_map.get(s) for s in server.get("uses_secrets", []) if runtime_map.get(s)}
    for k, v in non_secret.items():
        expanded = _substitute_env_vars(str(v))
        if not (expanded.strip("${}") in secret_runtimes and expanded.startswith("${")):
            result[k] = expanded
    return result

def _wrap_with_epos_secrets(server: dict, runtime_map: dict[str, str]) -> tuple[list[str], dict[str, str]]:
    uses_secrets = server.get("uses_secrets", [])
    runtime_names = [runtime_map[s] for s in uses_secrets if s in runtime_map]
    if len(runtime_names) < len(uses_secrets):
        missing = [s for s in uses_secrets if s not in runtime_map]
        print(f"ERROR: server '{server['name']}' uses_secrets missing: {missing}", file=sys.stderr)
        sys.exit(1)

    cmd = [server["command"]] + server.get("args", [])
    epos_secrets = str(_EPOS_SECRETS)
    python_cmd = "python3"

    if runtime_names:
        wrapped = [epos_secrets, "--only", ",".join(runtime_names), "--"] + cmd
    else:
        wrapped = [epos_secrets, "--"] + cmd

    return wrapped, _build_env_block(server, runtime_map)

def _build_json_entry(server: dict, runtime_map: dict[str, str], format_style: str) -> dict:
    t = server["transport"]
    is_copilot_cli = (format_style == "copilot_cli")
    
    if t in ("http", "sse"):
        entry = {"type": t, "url": server["url"]}
        if is_copilot_cli:
            entry["tools"] = ["*"]
        return entry
    elif t == "stdio":
        cmd, env = _wrap_with_epos_secrets(server, runtime_map)
        entry = {
            "type": "local" if is_copilot_cli else "stdio",
            "command": cmd[0],
            "args": cmd[1:]
        }
        if env:
            entry["env"] = env
        if is_copilot_cli:
            entry["tools"] = ["*"]
        return entry
    return {}

def _generate_json(content: str, format_style: str, active: list[dict], all_srv: list[dict], rmap: dict[str, str], merge: bool) -> str:
    data = json.loads(content) if content.strip() else {}
    
    format_key = "servers" if format_style == "servers" else "mcpServers"
    
    if not merge:
        data[format_key] = {}
    elif format_key not in data:
        data[format_key] = {}

    data["_generator"] = _GENERATOR_NOTE
    active_names = {s["name"] for s in active}
    
    for s in all_srv:
        if s["name"] not in active_names:
            data[format_key].pop(s["name"], None)
            
    for s in active:
        entry = _build_json_entry(s, rmap, format_style)
        if entry:
            data[format_key][s["name"]] = entry
            
    return json.dumps(data, indent=2) + "\n"

def _generate_toml(content: str, active: list[dict], all_srv: list[dict], rmap: dict[str, str], is_project: bool) -> str:
    lines = content.splitlines() if content.strip() else []
    out = []
    skip = False
    all_names = {s["name"] for s in all_srv}
    
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[mcp_servers.") and stripped.endswith("]"):
            name = stripped[13:-1].split(".")[0]
            skip = (name in all_names)
        elif stripped.startswith("[") and stripped.endswith("]"):
            skip = False
            
        if stripped.startswith("# Generated by sync-mcp.py") or stripped.startswith("# sync-mcp.py \u2014 DO NOT EDIT"):
            continue
            
        if not skip:
            out.append(line)
            
    while out and out[-1].strip() == "":
        out.pop()
        
    if out:
        out.append("")
        
    for s in active:
        name = s["name"]
        t = s["transport"]
        if not is_project:
            out.append(f"# {_GENERATOR_NOTE}")
        out.append(f"[mcp_servers.{name}]")
        out.append("enabled = true")
        if t in ("http", "sse"):
            out.append(f'type = "{t}"')
            out.append(f'url = "{s["url"]}"')
        elif t == "stdio":
            out.append('type = "stdio"')
            cmd, env = _wrap_with_epos_secrets(s, rmap)
            out.append(f'command = "{cmd[0]}"')
            out.append(f'args = {json.dumps(cmd[1:])}')
            if env:
                out.append(f"[mcp_servers.{name}.env]")
                for k, v in env.items():
                    out.append(f'{k} = {json.dumps(v)}')
        out.append("")

    res = "\n".join(out) + "\n"
    if is_project:
        res = _TOML_GENERATOR_HEADER + res.lstrip()
    return res

def _atomic_write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise

def main():
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        return 0

    check_mode = "--check" in sys.argv
    write_user = "--user" in sys.argv

    if not _TOML_SOURCE.exists():
        print(f"ERROR: {_TOML_SOURCE} not found.", file=sys.stderr)
        return 1

    with _TOML_SOURCE.open("rb") as fh:
        config = tomllib.load(fh)
    all_srv = config.get("server", [])
    rmap = _build_runtime_name_map()

    writes = {}
    for p in DEV_PRODUCTS:
        fmt = p["format"]
        for scope in ["project", "user"]:
            path = p[f"{scope}_path"]
            if not path: 
                continue
                
            active = [s for s in all_srv if s.get("scope", "project") == scope]
            exist = path.read_text(encoding="utf-8") if path.exists() else ""
            if fmt in ("mcpServers", "servers", "copilot_cli"):
                new_c = _generate_json(exist, fmt, active, all_srv, rmap, merge=(scope == "user"))
            elif fmt == "toml_mcp_servers":
                new_c = _generate_toml(exist, active, all_srv, rmap, is_project=(scope == "project"))
            else:
                continue
                
            writes[path] = new_c

    if check_mode:
        drift = False
        for path, new_c in writes.items():
            is_user_path = path.is_relative_to(pathlib.Path.home()) and not path.is_relative_to(_REPO_ROOT)
            if is_user_path and not write_user:
                continue
                    
            exist = path.read_text(encoding="utf-8") if path.exists() else ""
            if new_c != exist:
                drift = True
                diff = difflib.unified_diff(
                    exist.splitlines(keepends=True),
                    new_c.splitlines(keepends=True),
                    fromfile=f"{path} (on-disk)",
                    tofile=f"{path} (generated)",
                )
                print(f"\nDrift detected in {path}:")
                sys.stdout.writelines(diff)
        if drift:
            print("\nRun: python .eposforge/tool-transport/mcp-stdio-and-http/scripts/sync-mcp.py [--user]", file=sys.stderr)
            return 1
        print("OK \u2014 configs are in sync with mcp.servers.toml.")
        return 0

    for path, new_c in writes.items():
        if path.is_relative_to(pathlib.Path.home()) and not path.is_relative_to(_REPO_ROOT):
            if not write_user:
                continue
        _atomic_write(path, new_c)
        print(f"Written: {path}")

    if not write_user:
        print("\nNote: User-level configurations were skipped. Run with --user to write to $HOME paths.")
        
    print("\nReload your IDE / Claude Code session to pick up the updated MCP config.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
