#!/usr/bin/env python3
"""check-component-links.py

Enforces the component-reference convention (see
04-standards/01-naming-conventions/naming-conventions.md#component-references).

The Component Catalog at 01-architecture/02-components/README.md is the single
source of truth: its roster table maps each canonical component name to its
contract file. This script parses that table, then:

  --check [paths...]     Fail if any scanned Markdown file
                           * uses a numeric component identifier (C4, Component 14),
                           * references the deprecated "Router" component name, or
                           * uses a component shortcut/reference link whose
                             definition is missing or points at a missing file.
                         With no paths, scans the default doc scope.

  --write-defs <file>    Rewrite <file>'s trailing "<!-- component-links -->"
                         definitions block to cover exactly the component
                         labels it references (shortcut [Name] or full
                         reference [text][Name]), with correct relative paths.

Deterministic and dependency-free (stdlib only). Detecting *unbracketed*
component names that ought to be links is a semantic judgment left to the
docs-lint skill, not this floor.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

# scripts/ -> github-and-actions/ -> source-control-ci/ -> .eposforge/ -> repo root
REPO_ROOT = Path(__file__).resolve().parents[4]
CATALOG = REPO_ROOT / "01-architecture" / "02-components" / "README.md"

DEFAULT_SCOPE = [
    "00-vision", "01-architecture", "02-roadmap", "03-research",
    "04-standards", "AGENTS.md",
]

BLOCK_START = "<!-- component-links (generated by check-component-links.py --write-defs) -->"
# Any HTML comment whose text starts with "component-links" opens the block.
BLOCK_MARKER_RE = re.compile(r"<!--\s*component-links\b.*?-->", re.IGNORECASE)

# A numeric component identifier used as a reference: C4, C14, "Component 14",
# "component 6". Word-boundaried so it will not match e.g. "C4H8" or years.
NUMERIC_REF_RE = re.compile(r"\bC\d{1,2}\b|\bcomponent\s+\d{1,2}[a-z]?\b", re.IGNORECASE)

# Deprecated component name. "Router" capitalized as a component (not the
# lowercase "model router" concept, and not inside an allow-marked file).
ROUTER_REF_RE = re.compile(r"\bRouter\b")
# A file may opt out of the Router check with an HTML comment whose text
# starts with "allow-router" (e.g. the Orchestrator contract's deprecation note).
ALLOW_ROUTER_MARKER = "<!-- allow-router"

# Markdown reference usages: shortcut [Label] and full [text][Label].
# Group 'full' captures the label in [text][Label]; group 'short' in [Label].
# Markdown treats `](`/`][`/`]:` as a link/ref/def only when adjacent (no
# space), so the lookahead rejects only an *immediately* following ( [ :.
REF_USE_RE = re.compile(
    r"\[[^\]]+\]\[(?P<full>[^\]]+)\]"       # [text][Label]
    r"|(?<!\])\[(?P<short>[^\]^][^\]]*)\](?![(\[:])"  # [Label] not link/def/ref
)


def load_catalog() -> dict[str, str]:
    """Return {lowercased canonical name: contract filename} from the catalog table."""
    if not CATALOG.exists():
        sys.exit(f"ERROR: component catalog not found at {CATALOG}")
    mapping: dict[str, str] = {}
    row_re = re.compile(r"^\|\s*(?P<name>[^|]+?)\s*\|\s*\[[^\]]+\]\((?P<file>[^)]+)\)\s*\|")
    for line in CATALOG.read_text(encoding="utf-8").splitlines():
        m = row_re.match(line)
        if not m:
            continue
        name = m.group("name").strip()
        if name.lower() in ("component", "---"):  # header / divider
            continue
        mapping[name.lower()] = m.group("file").strip()
    if not mapping:
        sys.exit(f"ERROR: no roster rows parsed from {CATALOG}")
    return mapping


def iter_markdown(paths: list[str]) -> list[Path]:
    out: list[Path] = []
    for p in paths:
        ap = (REPO_ROOT / p) if not os.path.isabs(p) else Path(p)
        if ap.is_dir():
            out.extend(sorted(ap.rglob("*.md")))
        elif ap.suffix == ".md":
            out.append(ap)
    return out


def blank_code(text: str) -> str:
    """Return text with fenced blocks and inline code spans blanked to spaces,
    preserving every character offset and line so positions still map to the
    original. Illustrative code (e.g. a `C4` example of a *forbidden* form) must
    not be scanned as a live reference."""
    out: list[str] = []
    in_fence = False
    for line in text.split("\n"):
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            out.append(" " * len(line))
        elif in_fence:
            out.append(" " * len(line))
        else:
            out.append(re.sub(r"`[^`]*`", lambda m: " " * len(m.group(0)), line))
    return "\n".join(out)


def split_at_marker(text: str) -> tuple[str, str, int]:
    """(scannable_body, real_block, marker_index). Detection uses code-blanked
    text so an example block inside a fence is not mistaken for the real one;
    the returned block is the untouched original after the marker."""
    scannable = blank_code(text)
    m = BLOCK_MARKER_RE.search(scannable)
    idx = m.start() if m else len(text)
    return scannable[:idx], text[idx:] if m else "", idx


def referenced_labels(body: str, catalog: dict[str, str]) -> list[str]:
    """Canonical labels (original catalog casing) referenced in body, in first-seen order."""
    # Map lowercased -> canonical display name from the catalog table headers.
    display = {k: k for k in catalog}  # keys are already lowercased canonical
    seen: list[str] = []
    for m in REF_USE_RE.finditer(body):
        label = (m.group("full") or m.group("short") or "").strip()
        key = label.lower()
        if key in catalog and key not in seen:
            seen.append(key)
    # Return canonical display casing by re-reading the catalog line casing.
    return seen


def canonical_display_names() -> dict[str, str]:
    """{lowercased: original-cased} canonical names, from the catalog table."""
    out: dict[str, str] = {}
    row_re = re.compile(r"^\|\s*(?P<name>[^|]+?)\s*\|\s*\[")
    for line in CATALOG.read_text(encoding="utf-8").splitlines():
        m = row_re.match(line)
        if not m:
            continue
        name = m.group("name").strip()
        if name.lower() in ("component", "---"):
            continue
        out[name.lower()] = name
    return out


def rel_from(file: Path, target_filename: str) -> str:
    """Relative POSIX path from `file`'s directory to the target contract."""
    target = (REPO_ROOT / "01-architecture" / "02-components" / target_filename).resolve()
    rel = os.path.relpath(target, start=file.parent)
    rel = Path(rel).as_posix()
    return rel if rel.startswith(".") else f"./{rel}"


def write_defs(file: Path, catalog: dict[str, str]) -> bool:
    text = file.read_text(encoding="utf-8")
    scan_body, _, idx = split_at_marker(text)
    real_body = text[:idx].rstrip("\n")
    labels = referenced_labels(scan_body, catalog)
    display = canonical_display_names()
    if not labels:
        new_text = real_body + "\n"
    else:
        lines = [BLOCK_START]
        for key in labels:
            lines.append(f"[{display[key]}]: {rel_from(file, catalog[key])}")
        new_text = real_body + "\n\n" + "\n".join(lines) + "\n"
    if new_text != text:
        file.write_text(new_text, encoding="utf-8")
        return True
    return False


def defined_labels(block: str) -> dict[str, str]:
    """{lowercased label: target} from a definitions block."""
    out: dict[str, str] = {}
    for m in re.finditer(r"^\[([^\]]+)\]:\s*(\S+)\s*$", block, re.MULTILINE):
        out[m.group(1).strip().lower()] = m.group(2).strip()
    return out


def check(paths: list[str], catalog: dict[str, str]) -> int:
    errors: list[str] = []
    for file in iter_markdown(paths):
        try:
            rel = file.relative_to(REPO_ROOT)
        except ValueError:
            rel = file
        text = file.read_text(encoding="utf-8")
        scan_body, block, _ = split_at_marker(text)
        allow_router = ALLOW_ROUTER_MARKER in text

        for i, line in enumerate(scan_body.splitlines(), 1):
            for m in NUMERIC_REF_RE.finditer(line):
                errors.append(f"{rel}:{i}: numeric component reference '{m.group(0)}' — use the component name")
            if not allow_router:
                for m in ROUTER_REF_RE.finditer(line):
                    errors.append(f"{rel}:{i}: deprecated component name 'Router' — use 'Orchestrator'")

        defs = defined_labels(block)
        for key in referenced_labels(scan_body, catalog):
            if key not in defs:
                errors.append(f"{rel}: references [{key}] but no definition in the component-links block (run --write-defs)")
                continue
            target = (file.parent / defs[key]).resolve()
            if not target.exists():
                errors.append(f"{rel}: component link [{key}] -> {defs[key]} points at a missing file")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        print(f"\n{len(errors)} component-link violation(s).", file=sys.stderr)
        return 1
    print("component-links: OK")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="validate references (CI mode)")
    g.add_argument("--write-defs", metavar="FILE", help="regenerate a file's definitions block")
    ap.add_argument("paths", nargs="*", help="files/dirs to check (default: doc scope)")
    args = ap.parse_args()

    catalog = load_catalog()
    if args.write_defs:
        changed = write_defs(Path(args.write_defs).resolve(), catalog)
        print(f"{'updated' if changed else 'unchanged'}: {args.write_defs}")
        return 0
    return check(args.paths or DEFAULT_SCOPE, catalog)


if __name__ == "__main__":
    raise SystemExit(main())
